package openlync.forms;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;

public class FormSobre extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	/** Creates new form FormSobre */
	public FormSobre() {
		initComponents();

		setLocationRelativeTo(null);
		setResizable(false);

		jLabel6.setForeground(new Color(250, 0, 0));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		BtnFechar = new javax.swing.JButton();
		BtnLicenca = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();

		setTitle("OpenLync | Sobre");

		jPanel1.setLayout(null);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/Imagens/OpenLync_logo_menor.png"))); // NOI18N
		jPanel1.add(jLabel1);
		jLabel1.setBounds(182, 20, 80, 80);

		jLabel2.setHorizontalAlignment(0);
		jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 16));
		jLabel2.setText("OpenLync");
		jPanel1.add(jLabel2);
		jLabel2.setBounds(3, 120, 440, 19);

		jLabel3.setHorizontalAlignment(0);
		jLabel3.setText("1.0 (beta)");
		jPanel1.add(jLabel3);
		jLabel3.setBounds(-1, 160, 440, 18);

		jLabel4.setHorizontalAlignment(0);
		jLabel4.setText("Comunicador Instant\u00e2neo Empresarial");
		jPanel1.add(jLabel4);
		jLabel4.setBounds(0, 190, 440, 18);

		jLabel5.setHorizontalAlignment(0);
		jLabel5.setText("Copyright 2014 Roberto Luiz Debarba");
		jPanel1.add(jLabel5);
		jLabel5.setBounds(3, 220, 440, 18);

		BtnFechar.setText("Fechar");
		BtnFechar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnFecharActionPerformed(evt);
			}
		});
		jPanel1.add(BtnFechar);
		BtnFechar.setBounds(350, 280, 82, 28);

		BtnLicenca.setText("Licen\u00e7a");
		BtnLicenca.setToolTipText("");
		BtnLicenca.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnLicencaActionPerformed(evt);
			}
		});
		jPanel1.add(BtnLicenca);
		BtnLicenca.setBounds(10, 280, 87, 28);

		jLabel6.setHorizontalAlignment(0);
		jLabel6.setText("OpenLync no GitHub");
		jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel6MouseClicked(evt);
			}
		});
		jPanel1.add(jLabel6);
		jLabel6.setBounds(3, 250, 440, 18);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 439,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel1,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317,
				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {
		java.net.URI uri = null;
		try {
			uri = new java.net.URI("https://github.com/RobertoDebarba/OpenLync");
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
		try {
			Desktop.getDesktop().browse(uri);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	private void BtnFecharActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	private void BtnLicencaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton BtnFechar;
	private javax.swing.JButton BtnLicenca;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}