/*
 * FormConfiguracao.java
 *
 * Created on __DATE__, __TIME__
 */

package openlync.forms;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import openlync.principal.Configuracao;

/**
 *
 * @author  __USER__
 */
public class FormConfiguracao extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;

	/** Creates new form FormConfiguracao */
	public FormConfiguracao() {
		initComponents();

		// Seta tema
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException | InstantiationException
				| IllegalAccessException | UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}
		SwingUtilities.updateComponentTreeUI(this);

		// Retira bordas
		((BasicInternalFrameUI) this.getUI()).setNorthPane(null); // retirar
																	// o
																	// painel
																	// superior
		((BasicInternalFrameUI) this.getUI()).setSouthPane(null); // retirar
																	// o
																	// painel
																	// inferior
		this.setBorder(null);// retirar bordas
		
		this.setBounds(0, 0, 515, 540);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btnSalvar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		btnPortaSocket = new javax.swing.JButton();
		btnIPDB1 = new javax.swing.JButton();
		btnUserDB = new javax.swing.JButton();
		btnPassDB = new javax.swing.JButton();

		getContentPane().setLayout(null);

		btnSalvar.setText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});
		getContentPane().add(btnSalvar);
		btnSalvar.setBounds(380, 480, 120, 50);

		btnCancelar.setText("Cancelar");
		btnCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelarActionPerformed(evt);
			}
		});
		getContentPane().add(btnCancelar);
		btnCancelar.setBounds(240, 480, 120, 50);

		jLabel1.setHorizontalAlignment(0);
		jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24));
		jLabel1.setText("Configurar:");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(0, 70, 510, 29);

		btnPortaSocket.setText("Porta de Conex\u00e3o Socket");
		btnPortaSocket.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPortaSocketActionPerformed(evt);
			}
		});
		getContentPane().add(btnPortaSocket);
		btnPortaSocket.setBounds(100, 300, 310, 50);

		btnIPDB1.setText("IP do Banco de Dados");
		btnIPDB1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnIPDB1ActionPerformed(evt);
			}
		});
		getContentPane().add(btnIPDB1);
		btnIPDB1.setBounds(100, 120, 310, 50);

		btnUserDB.setText("Usu\u00e1rio do Banco de Dados");
		btnUserDB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUserDBActionPerformed(evt);
			}
		});
		getContentPane().add(btnUserDB);
		btnUserDB.setBounds(100, 180, 310, 50);

		btnPassDB.setText("Senha do Banco de Dados");
		btnPassDB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPassDBActionPerformed(evt);
			}
		});
		getContentPane().add(btnPassDB);
		btnPassDB.setBounds(100, 240, 310, 50);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
		Configuracao.lerCfg();
		dispose();
	}

	private void btnPortaSocketActionPerformed(java.awt.event.ActionEvent evt) {
		String valor = JOptionPane.showInputDialog(null,
				"IP do Servidor de Mensagens", "Configurações", 1);
		if (valor != null) {
			try {
				int valorInt = Integer.parseInt(valor);
				Configuracao.setPortaSocket(valorInt);
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, valor
						+ " não é uma porta válida!", "Erro", 0);
			}
		}
	}

	private void btnPassDBActionPerformed(java.awt.event.ActionEvent evt) {
		String valor = JOptionPane.showInputDialog(null,
				"Senha do Banco de Dados", "Configurações", 1);
		if (valor != null) {
			Configuracao.setPassDB(valor);
		}
	}

	private void btnUserDBActionPerformed(java.awt.event.ActionEvent evt) {
		String valor = JOptionPane.showInputDialog(null,
				"Usuário do Banco de Dados", "Configurações", 1);
		if (valor != null) {
			Configuracao.setUserDB(valor);
		}
	}

	private void btnIPDB1ActionPerformed(java.awt.event.ActionEvent evt) {
		String valor = JOptionPane.showInputDialog(null,
				"IP do Banco de Dados", "Configurações", 1);
		if (valor != null) {
			Configuracao.setIpServidorDB(valor);
		}
	}

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
		Configuracao.gravarCfg();
		dispose();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnIPDB1;
	private javax.swing.JButton btnPassDB;
	private javax.swing.JButton btnPortaSocket;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JButton btnUserDB;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}